[FEAT] typescript support
SUI-Components/sui pull request #1614
Opened 2023-06-21 09:34 UTC by kikoruiz

2023-06-21 09:51 UTC, jordevo approved these changes

2023-12-18 19:50 UTC, nucliweb commented on packages/sui-mock/package.json
> +    "msw": "1.2.1"
![free-your-mind-gearing-up](https://github.com/SUI-Components/sui/assets/1307927/186bc95b-294a-4bea-8159-c072b28a2fdc)

2023-12-18 19:51 UTC, nucliweb approved these changes

2024-04-29 11:06 UTC, carlosvillu requested changes

2024-04-29 11:06 UTC, carlosvillu commented on packages/sui-jest/package.json
> +    "@swc/jest": "0.2.31",
```suggestion
    "@swc/jest": "0.2.24",
```

2024-05-03 07:07 UTC, andresz1 approved these changes

2024-05-06 08:22 UTC, oegea approved these changes

2024-05-06 08:23 UTC, carlosvillu approved these changes

2024-05-06 08:24 UTC, nucliweb approved these changes

2024-05-06 08:24 UTC, merged